/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as StockOrdersRouteImport } from './routes/stock-orders'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PharmaciesRouteImport } from './routes/pharmacies'
import { Route as DrugsRouteImport } from './routes/drugs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const StockOrdersRoute = StockOrdersRouteImport.update({
  id: '/stock-orders',
  path: '/stock-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmaciesRoute = PharmaciesRouteImport.update({
  id: '/pharmacies',
  path: '/pharmacies',
  getParentRoute: () => rootRouteImport,
} as any)
const DrugsRoute = DrugsRouteImport.update({
  id: '/drugs',
  path: '/drugs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/branches': typeof BranchesRoute
  '/dashboard': typeof DashboardRoute
  '/drugs': typeof DrugsRoute
  '/pharmacies': typeof PharmaciesRoute
  '/profile': typeof ProfileRoute
  '/sales': typeof SalesRoute
  '/stock-orders': typeof StockOrdersRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/branches': typeof BranchesRoute
  '/dashboard': typeof DashboardRoute
  '/drugs': typeof DrugsRoute
  '/pharmacies': typeof PharmaciesRoute
  '/profile': typeof ProfileRoute
  '/sales': typeof SalesRoute
  '/stock-orders': typeof StockOrdersRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/branches': typeof BranchesRoute
  '/dashboard': typeof DashboardRoute
  '/drugs': typeof DrugsRoute
  '/pharmacies': typeof PharmaciesRoute
  '/profile': typeof ProfileRoute
  '/sales': typeof SalesRoute
  '/stock-orders': typeof StockOrdersRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/branches'
    | '/dashboard'
    | '/drugs'
    | '/pharmacies'
    | '/profile'
    | '/sales'
    | '/stock-orders'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/branches'
    | '/dashboard'
    | '/drugs'
    | '/pharmacies'
    | '/profile'
    | '/sales'
    | '/stock-orders'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/branches'
    | '/dashboard'
    | '/drugs'
    | '/pharmacies'
    | '/profile'
    | '/sales'
    | '/stock-orders'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BranchesRoute: typeof BranchesRoute
  DashboardRoute: typeof DashboardRoute
  DrugsRoute: typeof DrugsRoute
  PharmaciesRoute: typeof PharmaciesRoute
  ProfileRoute: typeof ProfileRoute
  SalesRoute: typeof SalesRoute
  StockOrdersRoute: typeof StockOrdersRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-orders': {
      id: '/stock-orders'
      path: '/stock-orders'
      fullPath: '/stock-orders'
      preLoaderRoute: typeof StockOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacies': {
      id: '/pharmacies'
      path: '/pharmacies'
      fullPath: '/pharmacies'
      preLoaderRoute: typeof PharmaciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drugs': {
      id: '/drugs'
      path: '/drugs'
      fullPath: '/drugs'
      preLoaderRoute: typeof DrugsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BranchesRoute: BranchesRoute,
  DashboardRoute: DashboardRoute,
  DrugsRoute: DrugsRoute,
  PharmaciesRoute: PharmaciesRoute,
  ProfileRoute: ProfileRoute,
  SalesRoute: SalesRoute,
  StockOrdersRoute: StockOrdersRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
