# Generated by Django 5.2.15 on 2026-06-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_profile_pharmacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('pharmacist', 'Pharmacist'), ('store_manager', 'Manager')], max_length=20),
        ),
    ]
